// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScoreController from "./score_controller"
application.register("score", ScoreController)

import ScoreFormController from "./score_form_controller"
application.register("score-form", ScoreFormController)
