# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "lint"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
      - name: Enable Corepack
        run: corepack enable
      - name: Install npm packages
        run: yarn install --immutable
      # Add or replace any other lints here
      - name: rubocop
        run: bundle exec rubocop
      - name: slim-lint
        run: bundle exec slim-lint app/views -c config/slim_lint.yml
      - name: eslint
        run: yarn eslint ./app/javascript
      - name: prettier
        run: yarn prettier --check ./app/javascript
